### ISSUE TITLE
cant get it to work on windows

### ISSUE THREAD

**Issue by k1ng440** [766b/vscode-go-outliner#1]

**Comment by 766b** [comment]
Windows is what I use at the moment. Once you installed it, did it prompt you to install additional package (`go-outliner`)?

**Comment by k1ng440** [comment]
no, it didn't. even i had to manually install the vs code plugin, its cant download and install for some reason.

**Comment by 766b** [comment]
I just uninstalled extension and `go-outliner` package, then tried reinstalling everything trough VS Code and it worked fine.
Do you use latest version of VSCode (1.23)?
PS: Also if working directory has no Go files and you have not opened any Go files, then nothing should be displayed.

**Comment by k1ng440** [comment]
i am using the latest version of vscode.

this is the error i get while trying to install 
https://i.imgur.com/BMSyrrC.png

**Comment by 766b** [comment]
Tried it on Debian and installed without issues. Did some googling and found people having similar issues with installing extensions.

- Do you have same issue with any other extensions?
- Is there any errors in `Help` -> `Toggle Developer Tools` -> `Network` tab, when you try to install?

**Comment by corlinp** [comment]
With a manual download / install I get the following output:
```
5/7/2018 7:11:23 PM - Microsoft VSIX Installer
5/7/2018 7:11:23 PM - -------------------------------------------
5/7/2018 7:11:23 PM - Initializing Install...
5/7/2018 7:11:23 PM - Extension Details...
5/7/2018 7:11:23 PM - 	Identifier         : go-outliner
5/7/2018 7:11:23 PM - 	Name               : Go Outliner
5/7/2018 7:11:23 PM - 	Author             : 766b
5/7/2018 7:11:23 PM - 	Version            : 0.0.4
5/7/2018 7:11:23 PM - 	Description        : Go code outline explorer
5/7/2018 7:11:23 PM - 	Locale             : en-US
5/7/2018 7:11:23 PM - 	MoreInfoURL        : 
5/7/2018 7:11:23 PM - 	InstalledByMSI     : False
5/7/2018 7:11:23 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
5/7/2018 7:11:23 PM - 
5/7/2018 7:11:23 PM - 	SignatureState     : Unsigned
5/7/2018 7:11:23 PM - 	Supported Products : 
5/7/2018 7:11:23 PM - 		Microsoft.VisualStudio.Code
5/7/2018 7:11:23 PM - 			Version : 
5/7/2018 7:11:23 PM - 
5/7/2018 7:11:23 PM - 	References         : 
5/7/2018 7:11:23 PM - Signature Details...
5/7/2018 7:11:23 PM - 	Extension is not signed.
5/7/2018 7:11:23 PM - 
5/7/2018 7:11:23 PM - Searching for applicable products...
5/7/2018 7:11:23 PM - Found installed product - Microsoft Visual Studio Community 2015
5/7/2018 7:11:23 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/7/2018 7:11:23 PM - Found installed product - Global Location
5/7/2018 7:11:23 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by 766b** [comment]
@tornato7 according to the log, installer can not find `Visual Studio Code`

**Comment by 766b** [comment]
Since I pushed several updates, do those issues still occur?

**Comment by 766b** [comment]
Closed for lack of feedback. If you are experiencing the same issue, please open another issue with extension version and OS information.

**Comment by k1ng440** [comment]
sorry, I didn't get your messages. its seems to be working well.
