### ISSUE TITLE
when change settings, it pop up  "no id named outlinerExplorerExtensionView" tree view

### ISSUE THREAD

**Issue by leyle** [766b/vscode-go-outliner#11]
hello,when I edit settings, vscode pop up a error, It show as Chinese, it means 
" no registered ID as outlinerExplorerExtensionView  in tree view", 

and GO OUTLINER show nothing in its view .

**Comment by 766b** [comment]
What is your system information and what setting options do you have? Does it happen every time you launch or just when you edit the settings and save?

**Comment by leyle** [comment]
My OS is  MacOS 10.13.6
Vscode version is 1.25.1
it happened ervery time i edit settings, no matter what settings I edit, when I save it, vscode will pop up that error.  even if I just add a space line. 

this is my settings

```json
{
    "editor.fontFamily": "Monaco",
    "editor.fontSize": 16,

    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/*.pyc": true,
        "**/.DS_Store": true
    },
    "workbench.editor.enablePreview": false,
    "workbench.colorTheme": "Solarized Light",
    "window.zoomLevel": 0,
    "workbench.activityBar.visible": false,
    "workbench.startupEditor": "newUntitledFile",
    "workbench.statusBar.visible": true,
    "window.title": "${activeEditorMedium}",

    "go.goroot": "/usr/local/Cellar/go/1.10.3/libexec",
    "goOutliner.extendExplorerTab": true,
}
```

**Comment by 766b** [comment]
I was able to reproduce the issue on fresh install. Try the latest version and see if it resolves your issue.

**Comment by leyle** [comment]
Thank you, It's OK now.
