### ISSUE TITLE
ui improvement suggestion

### ISSUE THREAD

**Issue by arkadiam** [766b/vscode-go-outliner#2]
Based on screenshot it looks like there is no need to repeat type and function in front of every entry.

Type window might look like:
Type
  operationValidationBuilder
  paramTypable
....

Same for FUNCTIONS windows. It might look like:
  newParameterParser
  isAliasParam

instead of 
 func newParameterParser
 func isAliasParam

**Comment by 766b** [comment]
Yeah, I agree. Its kind of a carry over from old code I wrote, now that it's separate, and I added icons, it is kind of redundant. I will remove it soon.
