### ISSUE TITLE
Suggestion: move views into custom view container

### ISSUE THREAD

**Issue by lannonbr** [766b/vscode-go-outliner#5]
as seen in the release notes for VSCode 1.23, there is a new api to create custom view containers (as seen [here](https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar)). This could allow a clean explorer view and then a separate view just for the outline views for your extension.

Here's an example that was in the release notes: 

![custom view containers example](https://code.visualstudio.com/assets/updates/1_23/custom-views-container.png)

It's not something that is required to be done, but if a vscode user already has a ton of other views in the main explorer, it may be able to declutter the explorer.

**Comment by 766b** [comment]
Yeah, that something I intended, and will probably move it to a custom view.
